-- Generated by Mocodo 4.3.2 — improved types
CREATE TABLE PUPITRE
(
    id  INTEGER NOT NULL,
    nom VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE EVENEMENT
(
    id          INTEGER NOT NULL,
    type        VARCHAR(50),
    nom         VARCHAR(100),
    date        TIMESTAMP,
    duree       INTEGER, -- en minutes
    lieu        VARCHAR(100),
    description VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE GROUPE
(
    id  INTEGER NOT NULL,
    nom VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE HACHAGE
(
    id_mdp INTEGER NOT NULL, -- renommé depuis id_map pour cohérence avec la FK
    cle    VARCHAR(255),
    PRIMARY KEY (id_mdp)
);

CREATE TABLE FANFARON
(
    id_technique            INTEGER NOT NULL,
    identifiant             VARCHAR(42) UNIQUE,
    email                   VARCHAR(255) UNIQUE,
    prenom                  VARCHAR(42),
    nom                     VARCHAR(42),
    genre                   VARCHAR(20),
    contrainte_Alimentaire  VARCHAR(100),
    date_Creation           TIMESTAMP,
    date_Derniere_Connexion TIMESTAMP,
    est_Admin               BOOLEAN DEFAULT FALSE,
    id_mdp                  INTEGER NOT NULL,
    PRIMARY KEY (id_technique),
    FOREIGN KEY (id_mdp) REFERENCES HACHAGE (id_mdp)
);

CREATE TABLE APPARTENIR
(
    id_technique INTEGER NOT NULL,
    id_pupitre           INTEGER NOT NULL,
    PRIMARY KEY (id_technique, id_pupitre),
    FOREIGN KEY (id_technique) REFERENCES FANFARON (id_technique),
    FOREIGN KEY (id_pupitre) REFERENCES PUPITRE (id)
);

CREATE TABLE INSCRIRE
(
    id_technique INTEGER NOT NULL,
    id_evenement INTEGER NOT NULL,
    id_pupitre   INTEGER NOT NULL,
    statut       VARCHAR(50),
    PRIMARY KEY (id_technique, id_evenement, id_pupitre),
    FOREIGN KEY (id_technique) REFERENCES FANFARON (id_technique),
    FOREIGN KEY (id_evenement) REFERENCES EVENEMENT (id),
    FOREIGN KEY (id_pupitre) REFERENCES PUPITRE (id)
);

CREATE TABLE PARTICIPER
(
    id_technique INTEGER NOT NULL,
    id_groupe           INTEGER NOT NULL,
    PRIMARY KEY (id_technique, id_groupe),
    FOREIGN KEY (id_technique) REFERENCES FANFARON (id_technique),
    FOREIGN KEY (id_groupe) REFERENCES GROUPE (id)
);